# render.yaml
services:
  - type: web
    name: apple-leaf-backend
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker backend.main:app --workers 2 --bind 0.0.0.0:10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
    autoDeploy: true
